language: node_js
node_js:
- stable
addons:
  ssh_known_hosts: "$DEPLOY_IP"
install:
- yarn
script:
- echo "skipping tests"
before_install:
- openssl aes-256-cbc -K $encrypted_91e4fc595629_key -iv $encrypted_91e4fc595629_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
before_deploy:
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .travis/deploy.sh &&.travis/deploy.sh
